// <auto-generated />
using System;
using CSVParser.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSVParser.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231115153438_initialSQLiteDBCreate")]
    partial class initialSQLiteDBCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("CSVParser.Models.StarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("AbsoluteMagnitude")
                        .HasColumnType("REAL");

                    b.Property<float?>("ColorIndex")
                        .HasColumnType("REAL");

                    b.Property<float?>("Declination")
                        .HasColumnType("REAL");

                    b.Property<float?>("DistanceFromSolInParsecs")
                        .HasColumnType("REAL");

                    b.Property<float?>("Luminosity")
                        .HasColumnType("REAL");

                    b.Property<string>("MKSpectralType")
                        .HasColumnType("TEXT");

                    b.Property<float?>("ProperMotionDeclination")
                        .HasColumnType("REAL");

                    b.Property<float?>("ProperMotionRightAscension")
                        .HasColumnType("REAL");

                    b.Property<float?>("RadialVelocityKmPerSecond")
                        .HasColumnType("REAL");

                    b.Property<float?>("RightAscension")
                        .HasColumnType("REAL");

                    b.Property<float?>("V_Magnitude")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Stars");
                });
#pragma warning restore 612, 618
        }
    }
}
