// <auto-generated />
using CSVParser.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSVParser.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("CSVParser.Models.StarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AbsoluteMagnitude")
                        .HasColumnType("REAL");

                    b.Property<string>("ColorIndex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Declination")
                        .HasColumnType("REAL");

                    b.Property<double>("DistanceFromSolInParsecs")
                        .HasColumnType("REAL");

                    b.Property<double>("Luminosity")
                        .HasColumnType("REAL");

                    b.Property<string>("MKSpectralType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProperMotionDeclination")
                        .HasColumnType("REAL");

                    b.Property<double>("ProperMotionRightAscension")
                        .HasColumnType("REAL");

                    b.Property<double>("RadialVelocityKmPerSecond")
                        .HasColumnType("REAL");

                    b.Property<double>("RightAscension")
                        .HasColumnType("REAL");

                    b.Property<double>("V_Magnitude")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Stars");
                });
#pragma warning restore 612, 618
        }
    }
}
